### ISSUE TITLE
kubectl apply -f yaml/db_all_in_one.yaml The connection to the server localhost:8080 was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by SantiagoAndre** [TarsCloud/K8STARS#13]
![image](https://user-images.githubusercontent.com/29509374/96768717-c6276680-13a3-11eb-8a67-af6f4bd0b04e.png)

**Comment by defool** [comment]
It seems the problem is that kubectl can not connect to k8s, please see [this post](https://medium.com/@raj10x/configure-local-kubectl-to-access-remote-kubernetes-cluster-ee78feff2d6d).
