### ISSUE TITLE
baseserver 的yaml中的镜像的tag不应该用latest

### ISSUE THREAD

**Issue by freelw** [TarsCloud/K8STARS#22]
用latest会导致用之前的部署脚本跑不通

**Comment by defool** [comment]
可以把latest改成对应的版本号，比如v1.0.1，是已经有上传对应的镜像了，你可以提个PR或者我们晚点我们补上

**Comment by freelw** [comment]
ok
现在用大概一个月前的代码就有问题了，因为最新的镜像中找主控的时候已经引入了命名空间，原来的时候都是在default ns的，所以原来的部署代码就起不来了

**Comment by defool** [comment]
最新版本已支持
