### ISSUE TITLE
howto define the module conf template

### ISSUE THREAD

**Issue by auqf** [TarsCloud/K8STARS#28]
I have try run the tarsgateway in the k8s, but I met the follow problems:
1. In the /tars/conf/GatewayServer.conf file, i can not found the db config
2.  the start.sh file's content is /tars/bin/GatewayServer --config=/tars/conf/GatewayServer.conf, but the start log is: [init exception]:[TC_Config::parseFile]:fopen fail: /tars/bin/GatewayServer.conf :No such file or directory.  whether the conf file is specified in the binnary GatewayServer?
3. where can i modify the conf template to general the conf by tarscli genconf?

**Comment by defool** [comment]
You can set  `TARS_MERGE_CONF` for 'tarscli genconf'
Here is the example: **https://github.com/TarsCloud/K8STARS/blob/master/baseserver/cppregistry/Dockerfile#L12**
