### ISSUE TITLE
tars-registry 服务无法下线，不能和 pod 状态同步

### ISSUE THREAD

**Issue by wenbinye** [TarsCloud/K8STARS#29]
在 kubernetes 里把 tars-registry 的 Pod 删除后，在 web 界面中 tars-registry 对应的服务没有下线，仍然是 active 状态。在 web 界面上也无法将服务下线。这是正常的吗？

**Comment by defool** [comment]
服务下线依赖prestop，可以参考[这里](https://github.com/TarsCloud/K8STARS/blob/master/examples/simple/simpleserver.yaml#L29)的yaml配置，
另外要注意`terminationGracePeriodSeconds`要超过80秒（prestop时间）才行。

无法在web界面下线节点，如果因为意外退出没有删除pod，会有心跳机制来剔除pod的流量，也可以在tarsregistry的容器里运行`tarscli notify clean n`来删除已因无心跳而剔除流量的pod。
