### ISSUE TITLE
跟K8SFramework定位是怎么区分的

### ISSUE THREAD

**Issue by kikoroc** [TarsCloud/K8STARS#31]
请问`K8STARS`跟[K8SFramework](https://github.com/TarsCloud/K8SFramework)定位是怎么区分的？[K8SFramework](https://github.com/TarsCloud/K8SFramework)是升级版？

**Comment by ruanshudong** [comment]
两种TARS+K8S的实现机制,  K8SFramework实现方案中TARS和K8S的结合更紧密一些,  但是其中tars的几个组件改动也更大一些, 几乎都重写了

**Comment by kikoroc** [comment]
明白，试试K8SFramework的方案
